### ISSUE TITLE
Why is this hosted on CurseForge? If you put it on SMR then the mod manager will work with it.

### ISSUE THREAD

**Issue by Borketh** [HyCraftHD/Compact-Machinery#32]
You do seem to have followed the C++ modding docs thus far, so putting the mod where mod enthusiasts can access it shouldn't be much of an issue.

Some useful links:
[The Satisfactory modding discord server](https://discord.gg/TShj39G)
[Satisfactory Mod Repository](https://ficsit.app)

**Comment by HyCraftHD** [comment]
It has already been there for about a year.
https://ficsit.app/mod/4ujQw7uwf1BLv4

Either way this mod is outdated.
